name = "(F.B.P.) Future Battlefield Pack: Elite ACUS"
uid = "5t3edt-btz6-9438-h6ui-9287zt47fa4"
version = 1.0
copyright = "Copyright © 2019, CDRMV (aka CDR Deadalus)"
description = "'Future Battlefield Pack: Elite ACUS' is a Submod for F.B.P.:Legends It adds the ACU-HQ and three new ACU Classes into the Game."
author = "CDRMV (aka CDR Deadalus)"
url = "http://www.moddb.com/mods/fbp-future-battlefield-pack"
icon = "/mods/Future Battlefield Pack Elite ACUs/Icon.png" 
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
